// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4yFF7CNh-xPouXaAa44uDD9eVZmOQTfU',
    appId: '1:1050588380052:android:fddb1ea12d699a8f83ed81',
    messagingSenderId: '1050588380052',
    projectId: 'hiitgym-2ae99',
    databaseURL: 'https://hiitgym-2ae99-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiitgym-2ae99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHEIvhcwH016hP5fcyr917yoU62hifHVw',
    appId: '1:1050588380052:ios:16529bc85693ce4083ed81',
    messagingSenderId: '1050588380052',
    projectId: 'hiitgym-2ae99',
    databaseURL: 'https://hiitgym-2ae99-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hiitgym-2ae99.appspot.com',
    androidClientId: '1050588380052-37oag1gu9s9in7bupgon7od7n2id33cg.apps.googleusercontent.com',
    iosClientId: '1050588380052-028n60n4p0jqj3ldu97m5qqgtek3j75a.apps.googleusercontent.com',
    iosBundleId: 'com.example.newhiitgymfirebase2',
  );
}
